team/m2/features.md

Made features file and updated headings

Made Features file

---

team/m2/data.md
team/m2/roles.md
team/reports/emily-shaw.md

made the final version of data.md

final version of data.md

---

team/m2/roles.md
team/reports/shanzay-khan.md

Just final touches on own report and roles, adding final commit links. No need to review.

Finalized roles+report

---

team/m3/ObjectToken/DataForm.js
team/m3/ObjectToken/grid.js
team/m3/ObjectToken/styles.css

changes area still kept in ObjectToke so people can work with the original temp grid. if reviewer wants  to replace the original grid.js with this just delete the folder an move everything out.

made change to Dataform.js so that it is now fully interactable

---

team/m3/styles.css

Changed CSS to display grid at proper size

Fixed shrunken display of grid

---

team/m3/shanzay-khan/feature-sequence-diagram.md

Also reviewed problem.md to see if it needed to be adjusted for new milestone. It does not, as it still follows what the new requirements want, and we did not really deviate from the original solution to our problem. And also made the sequence diagram of the battlegrid feature I made. I might need to finish it up better with the loop later when the implementation is complete with everyone else's features so that I don't still have it explaining how you can click it and change the color of the grids to a couple of pre-set tile types. But that is something to be fixed later, take a look at the graph and make sure it looks fine, but overall not much review needed.

Added battle grid feature sequence diagram, created first draft of graph

---

team/m2/roles.md
team/m3/shanzay-khan/feature-sequence-diagram.md
team/reports/shanzay-khan.md

Just finishing up report, my top 3 commits, and my sequence diagram. Give the diagram a look to make sure it looks fine. I'm not sure if my diagram is complex enough or not, would love input.

Finishing up: Updating roles, reports, finalized sequence diagram

---

team/m3/main.html
team/m3/styles.css

I essentially moved all my diceRoller html code underneath Geri's dropdown content for his tile editing stuff. This way the UI and general look of the buttons are the same and looks more uniform. In CSS I just added two things at the very end of the entire file to control the placement of where the button appears and the size of the font.

DiceRoller(2): Adjusted placement of feature, implemented dropdown

---

team/m2/data.md
team/m2/roles.md
team/reports/casey-hammill.md

Updated data documentation on drawing feature to accurately reflect implementation, and personal documentation

Updated documentation on data, roles, and my report

---

team/m3/styles.css

there was a big red square i had for testing that i forgot to get rid of :)

Removed big red square in the middle of UI

---

team/m3/js/backend/SQLiteToken.js

Open #75, this is the SQLite database for Token, this is just the initial version for me to work with, will close issue when finish

Token-database: SQLite database for token

---

team/m3/backend/controllers/GridController.js
team/m3/backend/models/SQLiteGrid.js
team/m3/backend/routers/GridRouter.js
team/m3/backend/server.js

Created the database and  CRUD routes for Grid attributes and added them to server.js.

Grid Database and CRUD Routes

---

team/m3/backend/controllers/GridController.js
team/m3/backend/models/SQLiteGrid.js
team/m3/backend/routers/GridRouter.js
team/m3/backend/server.js

This is the first draft of the grid database stuff after reverting accidental changes to main

Grid database and routes created

---

team/m3/backend/controllers/BackgroundImageController.js
team/m3/backend/models/SQLiteBackgroundImage.js
team/m3/backend/routers/backgroundImageRouter.js
team/m3/backend/server.js
team/m3/frontend/js/backgroundImageClientSide.js

Created background image router, controller. Also wrote some code for the frontend

background image database

---

team/m3/backend/controllers/BackgroundImageController.js
team/m3/backend/routers/backgroundImageRouter.js

A few minor issues prevented the server from running

BG Database #104: Fixed file reference issues

---

.vscode/README.md

Added a first version of README to the website. I added specifically how to use the stuff related to grid and dice rolling. please be sure to add your own features and explain extensively how to use it! Not sure if we need to explain backend features? 
I added some quick explanations of other features I did not personally create. If you want to change the descriptions I added, you are welcome to.

README added #112 : Added first version of README, to explain to graders how to use website

---

README.md

Added instructions on paint mode. Feel free to add anything in your own additions or let me know if you want anything changed!

Adding Paint Mode section to readme

---

README.md
team/m3/backend/routers/tokenRoutes.js
team/m3/frontend/js/TileLogic.js
team/m3/frontend/js/imageForToken.js
team/m3/frontend/js/moveToken.js
team/m3/frontend/js/tokenFinal.js
team/m3/frontend/js/tokenForm.js

Open #118, Description: added to README and added comments to all token related file. Fixed token render method to work with gridState

Final-Token-update: Added all token related update

---

team/m3/frontend/index.html
team/m3/frontend/js/paint.js

Reduced size of canvas to prevent its data from being too large and sometimes crashing

Database #128: Fixing issue with canvas being too large, slowing down

---

README.md
team/m3/frontend/index.html
team/m3/frontend/js/mainUI.js
team/m3/frontend/js/paint.js
team/m3/frontend/styles.css

Implements changes from multiple branches, finalizing UI and ensuring all databases work as intended

UI and Database Fixes
